### ISSUE TITLE
can't find trained model checkpoints

### ISSUE THREAD

**Issue by bjarthur** [HySonLab/ML4Insects#2]
i'm stuck in on this step in the [tutorial](https://github.com/HySonLab/ML4Insects/blob/main/Tutorial_ModelTraining.ipynb):

```
epgs = EPGSegment(config, inference = False)
# load a trained model
cp = 'cnn1d.soybeanAphid.json'
epgs.load_checkpoint(cp)
```

the checkpoint file disappeared in the commits you made this evening.  am i just not finding it, or do you not plan to distribute trained models?

**Comment by DINHQuangDung1999** [comment]
I removed it because it was a corrupted file, and also was not saved in a proper format. I will upload another file later today. 
You might want to checkout a new update package (and the tutorial notebooks) where I fixed some bugs and add more option to the plot functions. You can install it by running `pip install DiscoEPG==0.0.10`. `EPGDataset` no longer requires renaming the recording names into `<folder_name>_<recording_name>`, and supports reading multiple dataset at a time by providing a list of dataset names.

**Comment by DINHQuangDung1999** [comment]
Hi Ben, I have uploaded the trained model of ours. Can you check it please?

**Comment by phuongdd** [comment]
Hi Ben,

I guess Dung helping you to fix the bug. I hope you can install and run the package successfully.

Let us know if you need further help or if if you would need us to collaborate and help your team with in-depth analyses.

Best,
Phuong

**Comment by bjarthur** [comment]
the "Load a pretrained model" still doesn't work:

```
>>> from DiscoEPG.utils import process_config
>>> config = process_config('ML4Insects/configs/cnn1d.twentyfour.raw.256.json')
>>> config
{'exp_name': 'awdawdawdw', 'dataset_name': 'twentyfour', 'window_size': 1024, 'hop_length': 1024, 'arch': 'cnn1d', 'method': 'raw', 'scale': True, 'outlier_filter': False, 'optimizer': 'Adam', 'n_epochs': 50, 'lr': 0.0001, 'batch_size': 256, 'scope': 1, 'data_path': 'C:\\Dung\\EPG_project\\data', 'device': 'cpu', 'timestamp': '2024-09-16 08:57:26'}
```

i then modify data_path and dataset_name to match my experiment:

```
% tree data
data
├── dataset
│   └── dataset.name0.A01
└── dataset_ANA
```

and get "no such file or directory" error:

```
>>> config['dataset_name']='dataset'
>>> config['data_path']='data'
>>> from DiscoEPG import EPGSegment
>>> epgs = EPGSegment(config, inference = False)
Training mode.
data/dataset
Loading data ...
dataset:   0%|                                                            | 0/1 [00:00<?, ?it/s][Errno 2] No such file or directory: 'data/dataset_ANA/dataset.name0.ANA'
dataset: 100%|████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.60it/s]
Done! Elapsed: 0.28428053855895996 s
```

strange, because i haven't even gotten to the step in the tutorial where a checkpoint is loaded.  so i proceed to do that:

```
>>> cp = 'cnn1d.twentyfour.pt'
>>> epgs.load_checkpoint(cp)
Traceback (most recent call last):
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/DiscoEPG/models/Segmentation.py", line 357, in load_checkpoint
    self.model = torch.load(f'./checkpoints/{path}')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/cnn1d.twentyfour.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/DiscoEPG/models/Segmentation.py", line 359, in load_checkpoint
    self.model = torch.load(f'./checkpoints/{self.config.arch}/{path}')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/cnn1d/cnn1d.twentyfour.pt'
```

"./checkpoints/cnn1d/cnn1d.twentyfour.pt" indeed doesn't exists, but "cnn1d.combined_data.pt" does:

```
% tree ML4Insects/checkpoints 
ML4Insects/checkpoints
└── cnn1d
    └── cnn1d.combined_data.pt
```

yet i still get a similar error:

```
>>> cp = 'cnn1d.combined_data.pt'
>>> epgs.load_checkpoint(cp)
Traceback (most recent call last):
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/DiscoEPG/models/Segmentation.py", line 357, in load_checkpoint
    self.model = torch.load(f'./checkpoints/{path}')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/cnn1d.combined_data.pt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/DiscoEPG/models/Segmentation.py", line 359, in load_checkpoint
    self.model = torch.load(f'./checkpoints/{self.config.arch}/{path}')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/arthurb/.conda/envs/epg/lib/python3.12/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/cnn1d/cnn1d.combined_data.pt'
```

**Comment by DINHQuangDung1999** [comment]
Hi Ben, 

Thanks for your feedback. I will release an update in a few hour to fix this bug. This mainly have to do with the path to the checkpoints directory, which is set to `./checkpoints` by default, meaning that you have to create a specific folder `checkpoint/cnn1d` and then put this checkpoint inside that folder. The new update will allow users to manually select the checkpoint directory.

**Comment by bjarthur** [comment]
you might want to make a similar change [here](https://github.com/HySonLab/ML4Insects/blob/main/package/DiscoEPG/models/Segmentation.py#L308) so that users can specify the full path to where they want the predictions saved.

**Comment by bjarthur** [comment]
also, should [this line](https://github.com/HySonLab/ML4Insects/blob/main/package/DiscoEPG/models/Segmentation.py#L289) only be executed if 'self.ana is not None'?  as is, `epgs.segment(recording_name='dataset.name0')` failes unless i have a .ana file for each .A0x file.

**Comment by DINHQuangDung1999** [comment]
Hi Ben, please check out the latest version by installing with `pip install DiscoEPG==0.0.16`. Some bug you mentioned are fixed, and I have made the dependencies automatically installed along with the package.

**Comment by bjarthur** [comment]
works, thanks so much!
